### PR TITLE
recommend bigger swapfile for image-install, too.

### PR DESCRIPTION
**Pull request by CarstenSchelp**
In README.md, advise user to enlarge swapfile so that numpy and scipy can be compiled during their installation.

### CODE REVIEW

**Comment by henkrijneveld** [comment]
Is this also necessary when you download the prefab image?

**Comment by CarstenSchelp** [comment]
Yes, it is. When the serval.sh script is started, a virtual python environment named "serval" is created. With numpy and scipy. Numpy and scipy arethen  installed using pip and both modules get compiled on the RPi. It's ok when this "first time only" step takes a lot of time, but it ultimately crashes because compiling scipy with a standard-sized swapfile is the mentioned "nono". 
As a "disclaimer": I did not test the prefab installation WITH an enlarged swapfile because the "from scratch" version worked just fine for me. But I think that a bigger swapfile is a prerequisite for a successfull installation. Maybe also you can work around it by making sure that numpy and scipy are already present on the image ... ?

**Comment by CarstenSchelp** [comment]
Oh, by the way - ever since raspian buster is around it is hard for apt-get to return the right wheel of a particular ssh library. This library, in turn, is required for pip.
This problem can easily be worked around by using a raspian buster image instead of stretch. I had no issues when using raspian buster light. Maybe even this would help to avoid some problems in the transition of serval from python 2 to python 3? Maybe.

**Comment by gmos** [comment]
Seems not to be required anymore on bigger Pi's

**Pull request closed without merging**
